-- ZyntraConfig
-- Central product catalogue and balance values. IDs map to products created
-- under the BACKROOMS: STAY QUIET [CO-OP HORROR] experience in Creator Dashboard.

local TokenPercentPerLevel = 0.05
local PCT = ("+%d%%"):format(math.floor(TokenPercentPerLevel * 100 + 0.5))

return {
	DataStoreName = "ZyntraPlayerData_v1",
	SupportLeaderboardDataStoreName = "ZyntraDonationLeaderboard_v2",
	SupportLeaderboardSize = 10,
	SupportLeaderboardRefreshSeconds = 90,
	TokenPercentPerLevel = TokenPercentPerLevel,
	LevelCompletionTokens = 2,

	-- FRIEND_BOOST_20260916. Additive, uncapped: +10% completion tokens per
	-- unique verified Roblox friend who was in the SAME round on the SAME server
	-- (ServerScriptService.FriendBoost states the interpretation in full). The
	-- fraction never rounds away -- ZyntraMonetization carries it on the profile
	-- as FriendBoostTenths and pays whole tokens as they are earned.
	FriendBoost = {PercentPerFriend = 10},

	ProtectionItem = {
		Key = "EntityProtection",
		Name = "Entity Shield",
		TokenCost = 5,
		DurationSeconds = 5,
		Description = "Buy a stored charge for 5 seconds of protection. Activate it during a run.",
	},

	-- Stored consumables. Bought with Research Tokens, kept on the profile, spent
	-- during a round from the HUD. Description is what the shop and the daily
	-- rewards page render verbatim, so each one states its cost and its limits in
	-- the same words the server enforces.
	Items = {
		SpeedPotion = {
			Name = "Speed Potion",
			PreviewDescription = "CONSUMABLE · 1 stored potion. +30% movement speed for 6s. One use per round. No stamina change.",
			TokenCost = 3,
			DurationSeconds = 6,
			SpeedMultiplier = 1.30,
			MaxUsesPerRound = 1,
			-- Crate art generated by Codex on 2026-09-16 (assets/shop/box-speed-potion.png);
			-- the wall shop and the terminal's supplies card both draw it.
			IconId = 73457681182843,
			Description = "Costs 3 Research Tokens. Drink it during a run to move 30% faster for 6 seconds. One per round, it does not stack, and it changes nothing about your stamina.",
		},
		RouteMarker = {
			Name = "Route Marker Pack",
			PreviewDescription = "CONSUMABLE · 3 stored markers. Your team sees them; at most 3 of yours remain placed. Placed markers disappear when the round ends.",
			TokenCost = 2,
			PackSize = 3,
			MaxActive = 3,
			-- Crate art generated by Codex on 2026-09-16 (assets/shop/box-route-marker-pack.png).
			IconId = 100856675462356,
			Description = "Costs 2 Research Tokens for 3 markers. Place one to point a direction your whole team can see. Up to 3 of yours stand at a time, and they are cleared when the round ends.",
		},
	},

	-- Daily rewards. Playtime only accrues while a round is actually being played
	-- (ZyntraMonetization owns the exact rules); milestones and the wheel both
	-- reset at 00:00 UTC. Weights ARE the odds the UI shows -- they total 100 on
	-- purpose so a percentage needs no arithmetic to explain.
	DailyRewards = {
		AfkGraceSeconds = 90,
		ActivityMinimumStuds = 1,
		FlushIntervalSeconds = 60,
		Milestones = {
			{Minutes = 5, Reward = {Kind = "Tokens", Amount = 1}},
			{Minutes = 15, Reward = {Kind = "Item", Key = "SpeedPotion", Amount = 1}},
			{Minutes = 35, Reward = {Kind = "Item", Key = "EntityShield", Amount = 1}},
		},
		Wheel = {
			{Key = "Token1", Weight = 40, Label = "1 Research Token", Reward = {Kind = "Tokens", Amount = 1}},
			{Key = "Token3", Weight = 20, Label = "3 Research Tokens", Reward = {Kind = "Tokens", Amount = 3}},
			{Key = "Potion1", Weight = 20, Label = "1 Speed Potion", Reward = {Kind = "Item", Key = "SpeedPotion", Amount = 1}},
			{Key = "Potion2", Weight = 5, Label = "2 Speed Potions", Reward = {Kind = "Item", Key = "SpeedPotion", Amount = 2}},
			{Key = "Shield1", Weight = 10, Label = "1 Entity Shield", Reward = {Kind = "Item", Key = "EntityShield", Amount = 1}},
			-- Only Pool Service and Suburb Survey are eligible. The server records
			-- the exact unowned SkinId at spin time, or a 3-Token fallback when both
			-- are owned. The field stays Skin5 in either case, preserving the 5% odds.
			{Key = "Skin5", Weight = 5, Label = "Random Hazmat Skin", Reward = {Kind = "Skin"}},
		},
	},

	Studio = {
		GrantAllPasses = true,
		StartingTokens = 25,
	},

	Detector = {Range=120, HighRange=50, Cooldown=20, ReadingSeconds=4},
	Passes = {
  EntityDetector = {
   Id=1982715834, IconId=90757067349588, Name="Zyntra Entity Detector", Price=149,
   Description="Permanent detector. Press Z / D-pad left or tap SCAN during a run to scan for nearby threats. It reads LOW / MEDIUM / HIGH for 4 seconds and is ready again after 20 seconds. It never shows exact positions and cannot guarantee safety. Free simulated demo in the lobby shop.",
   PreviewDescription="PERMANENT · Scan nearby threats: LOW / MEDIUM / HIGH for 4 seconds. Ready again after 20 seconds. No exact positions, no guaranteed safety.",
  },
		Supporter = {
			Id = 1941938256,
			-- The previous asset was hazmat-themed and did not represent Supporter.
			-- Keep it retired until an approved replacement exists; the client renders
			-- this neutral Zyntra monogram instead of inventing or uploading artwork.
			IconId = 89100714759013,
			IconText = "Z//S",
			Name = "Zyntra Supporter",
			Price = 99,
			TokenGrant = 10,
			Description = "Receive 10 Research Tokens once and unlock a permanent ZYNTRA SUPPORTER tag.",
		},
		AdvancedEquipment = {
			Id = 1945402536,
			IconId = 105990911046404,
			Name = "Advanced Equipment",
			PreviewDescription = "PERMANENT · Focused torch (+45% range, same drain), +50% base stamina, hazmat colors and one +5% stamina/battery upgrade. Demo includes colors.",
			StaminaBonus = 0.50, -- additive capacity bonus; existing upgrades remain
			Price = 149,
			Description = "Permanent focused flashlight: a narrower beam with 45% more range and the same battery drain. Press Y / R3 or hold the torch on touch to switch. Includes permanent +50% base stamina on top of existing upgrades, hazmat colors and one " .. PCT .. " Stamina/Battery upgrade. Existing owners get focus automatically.",
		},
		CosmeticEquipment = {
			Id = 1946086261,
			IconId = 120190657040752,
			Name = "Glowstick Customizer",
			PreviewDescription = "PERMANENT · Choose the color of every glowstick you deploy. Cosmetic only; preview colors on your avatar without buying.",
			Price = 99,
			Description = "Permanently unlock the glowstick color picker for every glowstick you deploy. Cosmetic only.",
		},
	},

	Products = {
		ExpeditionPack = {
			Id = 3713829859,
			IconId = 132485864297801,
			Name = "Expedition Pack",
			PreviewDescription = "CONSUMABLE · 1 re-entry after death (10s protection), 1 shield charge (5s), 3 route markers. Stored until used. Repeatable purchase.",
			IconText = "PACK",
			Price = 69,
			BundleGrant = {Reentry = 1, Shield = 1, RouteMarkers = 3},
			Description = "Consumable pack: 1 stored Emergency Re-entry, 1 Entity Shield charge and 3 Route Markers. Use re-entry after dying; activate shield and markers from Equipment during a run. Repeatable purchase, not a permanent pass.",
		},
		Tokens4 = {
			Id = 3707755089,
			IconId = 106212286945374,
			Name = "4 Research Tokens",
			Price = 49,
			TokenGrant = 4,
			Description = "Adds 4 Research Tokens to your account. Spend tokens on permanent " .. PCT .. " Stamina or Battery upgrades, or buy one Entity Shield charge for 5 tokens.",
		},
		Tokens20 = {
			Id = 3707755233,
			IconId = 136487758639981,
			Name = "20 Research Tokens",
			Price = 149,
			TokenGrant = 20,
			Description = "Adds 20 Research Tokens to your account. Spend tokens on permanent " .. PCT .. " Stamina or Battery upgrades, or buy one Entity Shield charge for 5 tokens.",
		},
		EmergencyReentry = {
			Id = 3707755318,
			IconId = 137929784189814,
			Name = "Emergency Re-entry",
			Price = 29,
			ReentryGrant = 1,
			Description = "Adds 1 stored Emergency Re-entry credit. Return to your death location with 10 seconds invisible to monsters. Unsafe locations use nearby safe ground. Once per round.",
		},
	},

	-- Optional, repeatable donations with no gameplay grant. DonationRobux keeps
	-- these separate from utility receipts; their recorded totals share the
	-- support leaderboard. All six products belong to this experience; any future
	-- entry with a zero ID remains visibly disabled in the client.
	Donations = {
		DonationSignal = {
			Id = 3710116814,
			Order = 1,
			Name = "ZYNTRA Donate — Signal",
			Price = 10,
			Description = "Donate to the continued development of BACKROOMS: STAY QUIET [CO-OP HORROR].",
		},
		DonationSupply = {
			Id = 3710116945,
			Order = 2,
			Name = "ZYNTRA Donate — Supply",
			Price = 50,
			Description = "Donate to the continued development of BACKROOMS: STAY QUIET [CO-OP HORROR].",
		},
		DonationField = {
			Id = 3710117017,
			Order = 3,
			Name = "ZYNTRA Donate — Field",
			Price = 100,
			Description = "Donate to the continued development of BACKROOMS: STAY QUIET [CO-OP HORROR].",
		},
		DonationResearch = {
			Id = 3710117070,
			Order = 4,
			Name = "ZYNTRA Donate — Research",
			Price = 250,
			Description = "Donate to the continued development of BACKROOMS: STAY QUIET [CO-OP HORROR].",
		},
		DonationCommand = {
			Id = 3710117099,
			Order = 5,
			Name = "ZYNTRA Donate — Command",
			Price = 500,
			Description = "Donate to the continued development of BACKROOMS: STAY QUIET [CO-OP HORROR].",
		},
		DonationDirector = {
			Id = 3710117136,
			Order = 6,
			Name = "ZYNTRA Donate — Director",
			Price = 1000,
			Description = "Donate to the continued development of BACKROOMS: STAY QUIET [CO-OP HORROR].",
		},
		Donation5000 = {
			Id = 3713115025,
			Order = 7,
			Name = "ZYNTRA Donate — 5,000",
			Price = 5000,
			Description = "Optional, repeatable support for continued development. No gameplay advantages.",
		},
		Donation10000 = {
			Id = 3713115125,
			Order = 8,
			Name = "ZYNTRA Donate — 10,000",
			Price = 10000,
			Description = "Optional, repeatable support for continued development. No gameplay advantages.",
		},
		Donation20K = {
			Id = 1978617781,
			Kind = "GamePass",
			Order = 9,
			Name = "ZYNTRA Support — 20K",
			Price = 20000,
			Description = "One-time support through the existing 20K gamepass. No gameplay advantages.",
		},
	},

	-- Roblox badges, created on the Creator Dashboard under this same experience.
	-- 0 means "not created yet" and disables that award completely: no
	-- BadgeService call is made and nothing is recorded, so pasting the real id
	-- in later starts awarding it with no other change. Never invent an id here;
	-- an id that does not belong to this experience fails every award silently.
	Badges = {
		FirstClearLevel1 = 2788462628933614,
		FirstClearLevel2 = 349186155479685,
		FirstClearLevel3 = 457908347698355,
		-- Awarded the first time all three levels have been cleared at least
		-- once, which is NOT the same as clearing Level 3.
		CampaignComplete = 2318404539475574,
	},

	-- CHALLENGES_20260923 (Trello FnF49TWk): voluntary goals for a level you
	-- can already clear, and personal records. Nothing here gates the normal
	-- playthrough. The server times each escapee from RoundActive to their own
	-- escape; a run a developer tool changed is not recorded at all.
	--   Clean    = no Emergency Re-entry and no consumable aid used in the run.
	--   Equipped = the run had a paid permanent upgrade; shown next to the time,
	--              so a record never hides what it was set with.
	Challenges = {
		Levels = {1, 2, 3},
		-- PROVISIONAL goals in seconds. Tune them from the escaped times in
		-- zq_round_outcome once a week of data exists (first read 29/9).
		TimeGoalSeconds = {["1"] = 480, ["2"] = 600, ["3"] = 600},
		-- One-time tokens per level, paid in the same write that records the
		-- clear, so a challenge can be rewarded once and only once.
		RewardTokens = {NoDeath = 3, TimeGoal = 3},
	},

	-- Accessibility switches, in the order a settings surface should list them.
	-- Key is BOTH the player attribute the client reads and the profile.Settings
	-- field it is saved under, so these strings must keep matching their readers
	-- exactly: ReduceCameraShake (EntityShakeController, Level 2 Pool Foam
	-- Client), ReduceFlashing (Level 2 Pool Foam Client, Level 3 Lighting
	-- Controller) and the two caption names (Level 2 Pool Foam Client).
	-- Default is what a profile that never touched the switch
	-- publishes -- lobby music and captions default ON; other switches are
	-- off -- so a default must never be changed to the opposite of what
	-- its readers already assume.
	AccessibilitySettings = {
		{
			Key = "LobbyMusicEnabled",
			Label = "Lobby music",
			Description = "Turn background music in the lobby on or off. Level music and sound effects are unchanged.",
			Default = true,
		},
		{
			Key = "ReduceCameraShake",
			Label = "Reduce camera shake",
			Description = "Removes the entity's proximity tremble, chase rumble and footstep punch. Head-bob and crouch are unaffected.",
			Default = false,
		},
		{
			Key = "ReduceFlashing",
			Label = "Reduce flashing lights",
			Description = "Softens the strobing and full-screen flashes an encounter can throw at you.",
			Default = false,
		},
		{
			Key = "CaptionsEnabled",
			Label = "Show captions",
			Description = "Shows on-screen captions for sounds you would otherwise only hear.",
			Default = true,
		},
		-- The older half of the same caption pair, still read by the Pool Foam
		-- client (`DisableCaptions ~= true and CaptionsEnabled ~= false`). It is
		-- persisted and published so an existing save keeps working, but a UI
		-- that rendered both rows would contradict itself: show CaptionsEnabled
		-- and skip every entry marked Hidden.
		{
			Key = "DisableCaptions",
			Label = "Hide captions",
			Description = "Legacy switch kept for older saves. Use Show captions instead.",
			Default = false,
			Hidden = true,
		},
	},

	Colors = {
		HazmatDefault = Color3.fromRGB(210, 174, 58),
		GlowstickDefault = Color3.fromRGB(65, 145, 255),
	},
}
